### ISSUE TITLE
how fix

### ISSUE THREAD

**Issue by bibo318** [wolfbolin/crack-elasticsearch-by-docker#15]
[2024-09-17T15:20:16,882][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [node-2] deprecation component started
[2024-09-17T15:20:16,984][INFO ][o.e.t.TransportService   ] [node-2] publish_address {xxx:9300}, bound_addresses {xxxx:9300}
[2024-09-17T15:20:17,067][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-2] fatal error in thread [main], exiting
java.lang.NoSuchMethodError: 'void org.elasticsearch.license.License.<init>(int, java.lang.String, java.lang.String, java.lang.String, long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, long, int, int, long, org.elasticsearch.license.License$1)'
        at org.elasticsearch.license.License$Builder.build(License.java:940) ~[?:?]
        at org.elasticsearch.license.LicensesMetadata.<clinit>(LicensesMetadata.java:54) ~[?:?]
        at org.elasticsearch.xcontent.NamedXContentRegistry$Entry.lambda$new$0(NamedXContentRegistry.java:51) ~[elasticsearch-x-content-7.17.6.jar:7.17.6]
        at org.elasticsearch.xcontent.NamedXContentRegistry.parseNamedObject(NamedXContentRegistry.java:141) ~[elasticsearch-x-content-7.17.6.jar:7.17.6]
        at org.elasticsearch.xcontent.support.AbstractXContentParser.namedObject(AbstractXContentParser.java:408) ~[elasticsearch-x-content-7.17.6.jar:7.17.6]
        at org.elasticsearch.cluster.metadata.Metadata$Builder.fromXContent(Metadata.java:2081) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.gateway.PersistedClusterStateService.lambda$loadOnDiskState$1(PersistedClusterStateService.java:490) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.gateway.PersistedClusterStateService.consumeFromType(PersistedClusterStateService.java:555) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.gateway.PersistedClusterStateService.loadOnDiskState(PersistedClusterStateService.java:489) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.gateway.PersistedClusterStateService.loadBestOnDiskState(PersistedClusterStateService.java:413) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.gateway.PersistedClusterStateService.loadBestOnDiskState(PersistedClusterStateService.java:364) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:153) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.node.Node.start(Node.java:1183) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:335) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:443) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.6.jar:7.17.6]
        at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125) ~[elasticsearch-7.17.6.jar:7.17.6]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.6.jar:7.17.6]

**Comment by wolfbolin** [comment]
I'm not sure what you are doing to get this error. Was the patch package compiled correctly? Is it being replaced on all es nodes? Also it is highly recommended to upgrade your machine to 8.x. Because this version is easier to verify the correctness of the patch packages.

**Comment by bibo318** [comment]
I have done it successfully. The above error is due to my incorrect operation
